import type { Metadata } from "next";
import { Belgrano } from "next/font/google";
import "./globals.css";
import Provider from "@/context/Provider";

const belgrano = Belgrano({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Provider>
        <body className={belgrano.className}>{children}</body>
      </Provider>
    </html>
  );
}
